Add "osinfo_macros.h" to the installed headers
As the macros defined there are used in the public headers, this header
must be installed, otherwise we'll face errors such as:
```
/home/valabot/gnome3/include/libosinfo-1.0/osinfo/osinfo_entity.h:26:11: fatal error: osinfo/osinfo_macros.h: No such file or directory
   26 | # include "osinfo/osinfo_macros.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
```

Reported-by: Rico Tzschichholz <ricotz@ubuntu.com>
Signed-off-by: Rico Tzschichholz <ricotz@ubuntu.com>
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>