tree: goto cleanup on any error, on on_content_read()
Instead of just free'ing the CreateFromLocationAsyncData, let's just go
to cleanup, which will call create_from_location_async_data_free() and
return after that.

By doing so we avoid errors as:
g_task_return_error: assertion 'task->ever_returned' failed.

Reviewed-by: Daniel P. Berrangé <berrange@redhat.com>
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>