build: Disable -Wcast-warn
It causes issues when generating Libosinfo-scan.c on armv7hl.
```
Libosinfo-scan.c: In function ‘describe_type’:
/usr/include/glib-2.0/gobject/gtype.h:2299:6: error: cast increases required alignment of target type [-Werror=cast-align]
 2299 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
      |      ^
/usr/include/glib-2.0/gobject/gtype.h:484:66: note: in expansion of macro ‘_G_TYPE_CIC’
  484 | #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
      |                                                                  ^~~~~~~~~~~
/usr/include/glib-2.0/gobject/gparamspecs.h:216:45: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
  216 | #define G_PARAM_SPEC_INT64(pspec)          (G_TYPE_CHECK_INSTANCE_CAST ((pspec), G_TYPE_PARAM_INT64, GParamSpecInt64))
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
Libosinfo-scan.c:871:30: note: in expansion of macro ‘G_PARAM_SPEC_INT64’
  871 |     GParamSpecInt64 *pspec = G_PARAM_SPEC_INT64 (spec);
      |                              ^~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/gobject/gtype.h:2299:6: error: cast increases required alignment of target type [-Werror=cast-align]
 2299 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
      |      ^
/usr/include/glib-2.0/gobject/gtype.h:484:66: note: in expansion of macro ‘_G_TYPE_CIC’
  484 | #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
      |                                                                  ^~~~~~~~~~~
/usr/include/glib-2.0/gobject/gparamspecs.h:239:45: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
  239 | #define G_PARAM_SPEC_UINT64(pspec)         (G_TYPE_CHECK_INSTANCE_CAST ((pspec), G_TYPE_PARAM_UINT64, GParamSpecUInt64))
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
Libosinfo-scan.c:887:31: note: in expansion of macro ‘G_PARAM_SPEC_UINT64’
  887 |     GParamSpecUInt64 *pspec = G_PARAM_SPEC_UINT64 (spec);
      |                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/gobject/gtype.h:2299:6: error: cast increases required alignment of target type [-Werror=cast-align]
 2299 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
      |      ^
/usr/include/glib-2.0/gobject/gtype.h:484:66: note: in expansion of macro ‘_G_TYPE_CIC’
  484 | #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
      |                                                                  ^~~~~~~~~~~
/usr/include/glib-2.0/gobject/gparamspecs.h:354:45: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
  354 | #define G_PARAM_SPEC_DOUBLE(pspec)         (G_TYPE_CHECK_INSTANCE_CAST ((pspec), G_TYPE_PARAM_DOUBLE, GParamSpecDouble))
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
Libosinfo-scan.c:921:31: note: in expansion of macro ‘G_PARAM_SPEC_DOUBLE’
  921 |     GParamSpecDouble *pspec = G_PARAM_SPEC_DOUBLE (spec);
      |                               ^~~~~~~~~~~~~~~~~~~
Libosinfo-scan.c: In function ‘describe_default’:
/usr/include/glib-2.0/gobject/gtype.h:2299:6: error: cast increases required alignment of target type [-Werror=cast-align]
 2299 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
      |      ^
/usr/include/glib-2.0/gobject/gtype.h:484:66: note: in expansion of macro ‘_G_TYPE_CIC’
  484 | #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
      |                                                                  ^~~~~~~~~~~
/usr/include/glib-2.0/gobject/gparamspecs.h:216:45: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
  216 | #define G_PARAM_SPEC_INT64(pspec)          (G_TYPE_CHECK_INSTANCE_CAST ((pspec), G_TYPE_PARAM_INT64, GParamSpecInt64))
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
Libosinfo-scan.c:1004:30: note: in expansion of macro ‘G_PARAM_SPEC_INT64’
 1004 |     GParamSpecInt64 *pspec = G_PARAM_SPEC_INT64 (spec);
      |                              ^~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/gobject/gtype.h:2299:6: error: cast increases required alignment of target type [-Werror=cast-align]
 2299 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
      |      ^
/usr/include/glib-2.0/gobject/gtype.h:484:66: note: in expansion of macro ‘_G_TYPE_CIC’
  484 | #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
      |                                                                  ^~~~~~~~~~~
/usr/include/glib-2.0/gobject/gparamspecs.h:239:45: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
  239 | #define G_PARAM_SPEC_UINT64(pspec)         (G_TYPE_CHECK_INSTANCE_CAST ((pspec), G_TYPE_PARAM_UINT64, GParamSpecUInt64))
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
Libosinfo-scan.c:1010:33: note: in expansion of macro ‘G_PARAM_SPEC_UINT64’
 1010 |       GParamSpecUInt64 *pspec = G_PARAM_SPEC_UINT64 (spec);
      |                                 ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/gobject/gtype.h:2299:6: error: cast increases required alignment of target type [-Werror=cast-align]
 2299 |     ((ct*) g_type_check_instance_cast ((GTypeInstance*) ip, gt))
      |      ^
/usr/include/glib-2.0/gobject/gtype.h:484:66: note: in expansion of macro ‘_G_TYPE_CIC’
  484 | #define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)    (_G_TYPE_CIC ((instance), (g_type), c_type))
      |                                                                  ^~~~~~~~~~~
/usr/include/glib-2.0/gobject/gparamspecs.h:354:45: note: in expansion of macro ‘G_TYPE_CHECK_INSTANCE_CAST’
  354 | #define G_PARAM_SPEC_DOUBLE(pspec)         (G_TYPE_CHECK_INSTANCE_CAST ((pspec), G_TYPE_PARAM_DOUBLE, GParamSpecDouble))
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
Libosinfo-scan.c:1070:31: note: in expansion of macro ‘G_PARAM_SPEC_DOUBLE’
 1070 |     GParamSpecDouble *pspec = G_PARAM_SPEC_DOUBLE (spec);
      |                               ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>