Do not error out when inlining fails
-Winline causes error in GCC10, e.g

error: inlining failed in call to ‘OSINFO_LIST’: call is unlikely and code size would grow [-Werror=inline]

That particular macro, which will be introduced in the next commit, is
bas based on GLib own macros and it just so happens that if they were
also compiled with -Winline, the same error would happen [1]. Instead,
let just suppress those warnings.

[1] https://gitlab.gnome.org/GNOME/glib/issues/2042

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>