db: Remove useless /** PUBLIC METHODS */ comment
The comment is not exactly helpful and causes the following GTK-Doc
error:
```
../osinfo/osinfo_db.c:183: Error: Libosinfo: Skipping invalid GTK-Doc comment block:
/** PUBLIC METHODS */
^
```

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>