loader: Remove ueseless /** PUBLIC METHODS */ comment
The comment is not exactly helpful and causes the following GTK-Doc
error:
```
../osinfo/osinfo_loader.c:133: Error: Libosinfo: Skipping invalid GTK-Doc comment block:
/** PUBLIC METHODS */
^
```

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>