tree: cleanup on any error & return on _create_from_location_async_helper()
When calling a g_task_return_error(), we should also cleanup the
CreateFromLocationAsyncData and return immediately after that.

By doing so we avoid errors as:
g_task_return_error: assertion 'task->ever_returned' failed.

Reviewed-by: Daniel P. Berrangé <berrange@redhat.com>
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>